### ISSUE TITLE
Component hides when reach the boundary

### ISSUE THREAD

**Issue by rizwanahmed19** [gm0t/react-sticky-el#11]
Hey, I'm having a problem. When my component reaches the boundary of the parent element it hides, even though I've set the position of the `boundaryElement` to relative and `hideOnBoundaryHit` to false.

I don't know what I'm doing wrong.
Thanks.

**Comment by rizwanahmed19** [comment]
@gm0t

**Comment by gm0t** [comment]
Hi Rizwan! Could you please provide a code example for this issue?

**Comment by rizwanahmed19** [comment]
Yeah sure.
Here's the code where I'm using sticky, where SideCart is a custom component.
```jsx
<div className="shop-container">
...
  <div className="grid-container">
    <Grid>
      <Row>
        ...
        <Col xs={12} md={4}>
          <div className="sticky-container">
            <Sticky hideOnBoundaryHit={false} boundaryElement='.grid-container'>
              <SideCart shopId={shopId} />
            </Sticky>
          </div>
        </Col>
      </Row>
    </Grid>
  </div>
...
</div>
```
And here's the css:
```css
.grid-container {
  position: relative;
  background-color: #ededed;
  padding: 40px 0;
  margin-top: 40px;
  padding-left: 70px;
}
```
