### ISSUE TITLE
Can the sticky header follow the horizontal scrolling?

### ISSUE THREAD

**Issue by mrdulin** [gm0t/react-sticky-el#94]
```jsx
import './style.css';
import Sticky from 'react-sticky-el';

export const App = () => {
  const panels = [{ id: 1 }, { id: 2 }, { id: 3 }];

  return (
    <div className="wrapper">
      <div style={{ display: 'flex', marginTop: 40 }}>
        {panels.map((p) => (
          <div key={p.id} className="panel">
            <Sticky scrollElement=".wrapper">
              <div className="panel-header">header {p.id}</div>
            </Sticky>
            <div className="panel-content">content {p.id}</div>
          </div>
        ))}
      </div>
    </div>
  );
};
```

`style.scss`:
```css
.wrapper {
  position: relative;
  height: 300px;
  width: 600px;
  overflow: auto;
  border: 1px solid #ddd;
}

.panel-header {
  background-color: red;
}

.panel-content {
  background-color: yellow;
  height: 600px;
}

.panel {
  width: 200px;
  margin: 0 10px;
  flex-shrink: 0;
}
```

![image](https://github.com/gm0t/react-sticky-el/assets/17866683/fa33db9d-41b7-499c-b139-5edeaba766b1)

The sticky header does not follow the horizontal scrolling. 

[stackblitz](https://stackblitz.com/edit/stackblitz-starters-qzjmxw?file=src%2FApp.tsx)
